### ISSUE TITLE
py2neo Graph creation issue.using py2neo 4.0.0. version

### ISSUE THREAD

**Issue by Farzana-md** [weihesdlegend/Auto-complete-System#1] opened 2018-06-13 11:12 UTC
I have created Graph using 
def __init__(self,uri = "bolt://localhost:7687",username='neo4j', password='password'):
        self.graph = Graph(uri,user=username, password=password,auth=('neo4j', 'password'))

I have tried to change the port but I am getting the same issue.

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\py2neo\database.py", line 88, in __new__
    inst = cls._instances[key]
KeyError: 'd158bbdc01814f7bdce8ebe3a78d26bc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\machine_learning_ai_tasks\Auto-complete-System-master\app.py", line 49, in <module>
    app = Application(root)
  File "D:\machine_learning_ai_tasks\Auto-complete-System-master\app.py", line 16, in __init__
    self.app = Server()
  File "D:\machine_learning_ai_tasks\Auto-complete-System-master\src\Server.py", line 38, in __init__
    self.db = Database.DatabaseHandler()
  File "D:\machine_learning_ai_tasks\Auto-complete-System-master\src\Database.py", line 12, in __init__
    self.graph = Graph()
  File "D:\Python36\lib\site-packages\py2neo\database.py", line 298, in __new__
    database = Database(uri, **settings)
  File "D:\Python36\lib\site-packages\py2neo\database.py", line 97, in __new__
    user_agent=connection_data["user_agent"])
  File "D:\Python36\lib\site-packages\neo4j\v1\api.py", line 127, in __new__
    return subclass(uri, **config)
  File "D:\Python36\lib\site-packages\neo4j\v1\direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "D:\Python36\lib\site-packages\neo4j\v1\direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "D:\Python36\lib\site-packages\neo4j\bolt\connection.py", line 453, in acquire_direct
    connection = self.connector(address, self.connection_error_handler)
  File "D:\Python36\lib\site-packages\neo4j\v1\direct.py", line 70, in connector
    return connect(address, security_plan.ssl_context, error_handler, **config)
  File "D:\Python36\lib\site-packages\neo4j\bolt\connection.py", line 707, in connect
    raise last_error
  File "D:\Python36\lib\site-packages\neo4j\bolt\connection.py", line 697, in connect
    s = _connect(resolved_address, **config)
  File "D:\Python36\lib\site-packages\neo4j\bolt\connection.py", line 587, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error.errno))
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason 10061)

please provide some guidance to resolve the issue.

![image](https://user-images.githubusercontent.com/39991026/41347820-76d036c4-6f28-11e8-8acb-a9260aa088c8.png)

**Comment by weihesdlegend** [comment] 2018-06-14 05:20
Hi Farzana,
Thanks for trying out my app. 
The issue looks like database connection issue. 
I am assuming you are running `app.py` or `import app`? 
If so I tried the same thing but there is no issue. Below are information from my database. You can use any of the below method to access. 
`Version 3.3.3 Enterprise
Status RUNNING
HTTP port 7474
HTTPS port 7473
Bolt port 7687`
You should be able to connect without changing the default parameters in `DatabaseHandler.__init__()`
Please make sure that you have Neo4j database correctly installed. There is an app called Neo4j desktop, which allows you to visualize the data in the database. Verify that you can insert some simple values into DB using Py2Neo library.

**Comment by weihesdlegend** [comment] 2018-06-18 17:24
Closing for not reproducible.

**Closed by weihesdlegend** 2018-06-18 17:24 UTC
